/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/gpu_rtx.glb -o src/components/GPU_Model.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/gpu_rtx.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials['hard plastic']} position={[0.609, -0.569, -0.02]} scale={[1, 0.423, 0.45]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['hard plastic']} position={[0.609, 0.492, -0.02]} rotation={[0, 0, Math.PI]} scale={[1, 0.423, 0.45]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.plastic} position={[-0.867, 0.791, -0.155]} />
      <mesh geometry={nodes.RTX_3080_Ti.geometry} material={materials.logo} position={[-1.555, -0.105, 0.406]} rotation={[Math.PI / 2, 0, 0]} scale={0.284} />
      <group position={[-0.481, 0.882, 0.153]}>
        <mesh geometry={nodes.Plane012.geometry} material={materials['electronic(serkit board)']} />
        <mesh geometry={nodes.Plane012_1.geometry} material={materials.pcie} />
      </group>
      <mesh geometry={nodes.AO_shield.geometry} material={materials['IO shield']} position={[-2.183, -0.691, 0.055]} rotation={[-Math.PI, 0, 0]} scale={[0.316, 0.316, 0.229]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.plastic} position={[2.413, -0.038, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={0.871} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['hard plastic']} position={[-1.046, -0.037, 0.192]} scale={[1, 0.857, 0.211]} />
      <mesh geometry={nodes.main_cache.geometry} material={materials.Silver} position={[0.609, 0.071, -0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.167, 0.167, 0.05]} />
      <mesh geometry={nodes.heatsink002.geometry} material={materials.plastic} position={[0.373, -0.028, -0.03]} rotation={[Math.PI, 0, Math.PI]} scale={1.057} />
      <mesh geometry={nodes.fan_001.geometry} material={materials.plastic} position={[-1.067, -0.045, -0.385]} rotation={[-Math.PI, 0, -2.443]} />
      <mesh geometry={nodes.fan_alimentation001.geometry} material={nodes.fan_alimentation001.material} position={[-1.065, -0.045, -0.297]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.97, 1]} />
      <mesh geometry={nodes.fan_cache001.geometry} material={materials.plastic} position={[-1.044, -0.044, -0.572]} rotation={[Math.PI / 2, 0, 0]} scale={[0.827, 0.457, 0.827]} />
      <mesh geometry={nodes.fan_centre001.geometry} material={materials.plastic} position={[-1.065, -0.045, -0.292]} />
      <mesh geometry={nodes.fan_alimentation.geometry} material={materials['hard plastic']} position={[2.24, -0.045, 0.252]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 0.97, 1]} />
      <mesh geometry={nodes.fan_centre.geometry} material={materials.plastic} position={[2.24, -0.045, 0.257]} />
      <mesh geometry={nodes.fan_cache.geometry} material={materials.plastic} position={[2.261, -0.044, -0.023]} rotation={[Math.PI / 2, 0, 0]} scale={[0.827, 0.457, 0.827]} />
      <mesh geometry={nodes.fan_.geometry} material={materials.plastic} position={[2.24, -0.045, 0.355]} rotation={[0, 0, 0.698]} />
      <mesh geometry={nodes.heatsink.geometry} material={materials.plastic} position={[2.167, -0.028, -0.03]} />
      <mesh geometry={nodes.pcie_L2.geometry} material={materials['orange shit']} position={[-0.94, 1.037, 0.17]} />
      <mesh geometry={nodes.pcie_R2.geometry} material={materials['orange shit']} position={[0.259, 1.037, 0.169]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.006, -0.141, -0.033]} />
      <mesh geometry={nodes.pcie_L2001.geometry} material={materials['orange shit']} position={[-0.94, 1.037, 0.142]} />
      <mesh geometry={nodes.pcie_R2001.geometry} material={materials['orange shit']} position={[0.259, 1.037, 0.14]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[-0.006, -0.141, -0.033]} />
    </group>
  )
}

useGLTF.preload('/gpu_rtx.glb')
